name: Build & Deploy HTML5 Demo (Defold)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java (JDK 21)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Download latest stable bob.jar (Defold)
        run: |
          set -e
          mkdir -p .defold
          API_URL="https://api.github.com/repos/defold/defold/releases/latest"
          BOB_URL=$(curl -sSL "$API_URL" | jq -r '.assets[] | select(.name=="bob.jar") | .browser_download_url')
          echo "bob.jar = $BOB_URL"
          curl -L "$BOB_URL" -o .defold/bob.jar

      - name: Resolve, build and bundle (HTML5)
        run: |
          set -e
          java -jar .defold/bob.jar --version
          java -jar .defold/bob.jar --archive --platform js-web resolve build bundle \
            --bundle-output build/web

      - name: Flatten HTML5 bundle (move inner folder to build/web)
        run: |
          set -e
          # найдём папку, где лежит index.html
          BUNDLE_DIR=$(find build/web -type f -name index.html -printf '%h\n' | head -n1)
          echo "Detected bundle dir: $BUNDLE_DIR"
          if [ -n "$BUNDLE_DIR" ] && [ "$BUNDLE_DIR" != "build/web" ]; then
            rsync -a "$BUNDLE_DIR"/ build/web/
            # опционально подчистим прочие папки первого уровня
            find build/web -mindepth 1 -maxdepth 1 -type d ! -path "$BUNDLE_DIR" -exec rm -rf {} +
          fi
          test -f build/web/index.html || (echo "index.html not found in build/web" && exit 1)

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/web

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
