name: Build & Deploy HTML5 Demo (Defold)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java (JDK 21)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Download latest stable bob.jar (Defold)
        run: |
          set -e
          mkdir -p .defold
          API_URL="https://api.github.com/repos/defold/defold/releases/latest"
          BOB_URL=$(curl -sSL "$API_URL" | jq -r '.assets[] | select(.name=="bob.jar") | .browser_download_url')
          echo "bob.jar = $BOB_URL"
          curl -L "$BOB_URL" -o .defold/bob.jar

      - name: Resolve, build and bundle (HTML5)
        run: |
          set -e
          java -jar .defold/bob.jar --version
          java -jar .defold/bob.jar --archive --platform js-web resolve build bundle \
            --bundle-output build/web

      - name: Detect bundle dir
        id: bundle
        run: |
          set -e
          DIR=$(find build/web -type f -name index.html -printf '%h\n' | head -n1)
          echo "Bundle dir: $DIR"
          test -f "$DIR/index.html" || (echo "index.html not found" && exit 1)
          echo "dir=$DIR" >> "$GITHUB_OUTPUT"

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ steps.bundle.outputs.dir }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
