name: Build & Deploy HTML5 Demo (Defold)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java (JDK 21)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Download latest stable bob.jar (Defold)
        run: |
          set -e
          mkdir -p .defold
          # скачиваем bob.jar из последнего релиза Defold на GitHub
          BOB_URL=$(curl -sSL https://api.github.com/repos/defold/defold/releases/latest \
            | python - <<'PY'
import sys, json
data=json.load(sys.stdin)
print([a["browser_download_url"] for a in data["assets"] if a["name"]=="bob.jar"][0])
PY
          )
          echo "bob.jar: $BOB_URL"
          curl -L "$BO
